-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity simple_buff is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;  
    input_0_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_1_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_2_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_3_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_4_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_5_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_6_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_7_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_8_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_9_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_10_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_11_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_12_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_13_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_14_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_15_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_16_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_17_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_18_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_19_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_20_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_21_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_22_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_23_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_24_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_25_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_26_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_27_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_28_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_29_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_30_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_31_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_32_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_33_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_34_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_35_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_36_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_37_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_38_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_39_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_40_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_41_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_42_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_43_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_44_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_45_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_46_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_47_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_48_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_49_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_50_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_51_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_52_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_53_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_54_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_55_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_56_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_57_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_58_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_59_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_60_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_61_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_62_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_63_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_64_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_65_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_66_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_67_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_68_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_69_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_70_V : IN STD_LOGIC_VECTOR (63 downto 0);
    input_71_V : IN STD_LOGIC_VECTOR (63 downto 0);
    output_0_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_1_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_2_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_3_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_4_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_5_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_6_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_7_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_8_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_9_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_10_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_11_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_12_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_13_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_14_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_15_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_16_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_17_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_18_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_19_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_20_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_21_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_22_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_23_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_24_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_25_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_26_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_27_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_28_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_29_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_30_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_31_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_32_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_33_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_34_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_35_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_36_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_37_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_38_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_39_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_40_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_41_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_42_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_43_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_44_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_45_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_46_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_47_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_48_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_49_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_50_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_51_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_52_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_53_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_54_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_55_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_56_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_57_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_58_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_59_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_60_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_61_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_62_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_63_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_64_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_65_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_66_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_67_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_68_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_69_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_70_V : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_71_V : OUT STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of simple_buff is 
    signal grp_buffer_input_fu_1250_ap_return_0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_2 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_3 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_4 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_5 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_6 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_7 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_8 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_9 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_10 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_11 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_12 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_13 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_14 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_15 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_16 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_17 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_18 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_19 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_20 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_21 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_22 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_23 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_24 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_25 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_26 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_27 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_28 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_29 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_30 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_31 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_32 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_33 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_34 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_35 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_36 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_37 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_38 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_39 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_40 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_41 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_42 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_43 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_44 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_45 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_46 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_47 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_48 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_49 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_50 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_51 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_52 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_53 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_54 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_55 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_56 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_57 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_58 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_59 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_60 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_61 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_62 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_63 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_64 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_65 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_66 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_67 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_68 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_69 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_70 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_buffer_input_fu_1250_ap_return_71 : STD_LOGIC_VECTOR (63 downto 0);

    component buffer_input IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;  
        seed_0_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_1_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_2_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_3_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_4_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_5_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_6_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_7_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_8_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_9_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_10_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_11_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_12_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_13_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_14_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_15_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_16_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_17_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_18_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_19_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_20_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_21_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_22_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_23_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_24_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_25_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_26_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_27_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_28_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_29_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_30_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_31_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_32_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_33_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_34_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_35_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_36_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_37_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_38_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_39_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_40_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_41_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_42_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_43_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_44_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_45_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_46_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_47_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_48_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_49_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_50_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_51_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_52_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_53_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_54_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_55_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_56_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_57_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_58_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_59_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_60_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_61_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_62_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_63_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_64_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_65_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_66_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_67_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_68_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_69_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_70_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        seed_71_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_7 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_8 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_9 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_10 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_11 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_12 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_13 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_14 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_15 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_16 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_17 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_18 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_19 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_20 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_21 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_22 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_23 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_24 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_25 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_26 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_27 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_28 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_29 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_30 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_31 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_32 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_33 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_34 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_35 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_36 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_37 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_38 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_39 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_40 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_41 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_42 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_43 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_44 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_45 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_46 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_47 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_48 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_49 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_50 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_51 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_52 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_53 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_54 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_55 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_56 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_57 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_58 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_59 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_60 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_61 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_62 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_63 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_64 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_65 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_66 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_67 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_68 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_69 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_70 : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_return_71 : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;



begin
    grp_buffer_input_fu_1250 : component buffer_input
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        seed_0_V_read => input_0_V,
        seed_1_V_read => input_1_V,
        seed_2_V_read => input_2_V,
        seed_3_V_read => input_3_V,
        seed_4_V_read => input_4_V,
        seed_5_V_read => input_5_V,
        seed_6_V_read => input_6_V,
        seed_7_V_read => input_7_V,
        seed_8_V_read => input_8_V,
        seed_9_V_read => input_9_V,
        seed_10_V_read => input_10_V,
        seed_11_V_read => input_11_V,
        seed_12_V_read => input_12_V,
        seed_13_V_read => input_13_V,
        seed_14_V_read => input_14_V,
        seed_15_V_read => input_15_V,
        seed_16_V_read => input_16_V,
        seed_17_V_read => input_17_V,
        seed_18_V_read => input_18_V,
        seed_19_V_read => input_19_V,
        seed_20_V_read => input_20_V,
        seed_21_V_read => input_21_V,
        seed_22_V_read => input_22_V,
        seed_23_V_read => input_23_V,
        seed_24_V_read => input_24_V,
        seed_25_V_read => input_25_V,
        seed_26_V_read => input_26_V,
        seed_27_V_read => input_27_V,
        seed_28_V_read => input_28_V,
        seed_29_V_read => input_29_V,
        seed_30_V_read => input_30_V,
        seed_31_V_read => input_31_V,
        seed_32_V_read => input_32_V,
        seed_33_V_read => input_33_V,
        seed_34_V_read => input_34_V,
        seed_35_V_read => input_35_V,
        seed_36_V_read => input_36_V,
        seed_37_V_read => input_37_V,
        seed_38_V_read => input_38_V,
        seed_39_V_read => input_39_V,
        seed_40_V_read => input_40_V,
        seed_41_V_read => input_41_V,
        seed_42_V_read => input_42_V,
        seed_43_V_read => input_43_V,
        seed_44_V_read => input_44_V,
        seed_45_V_read => input_45_V,
        seed_46_V_read => input_46_V,
        seed_47_V_read => input_47_V,
        seed_48_V_read => input_48_V,
        seed_49_V_read => input_49_V,
        seed_50_V_read => input_50_V,
        seed_51_V_read => input_51_V,
        seed_52_V_read => input_52_V,
        seed_53_V_read => input_53_V,
        seed_54_V_read => input_54_V,
        seed_55_V_read => input_55_V,
        seed_56_V_read => input_56_V,
        seed_57_V_read => input_57_V,
        seed_58_V_read => input_58_V,
        seed_59_V_read => input_59_V,
        seed_60_V_read => input_60_V,
        seed_61_V_read => input_61_V,
        seed_62_V_read => input_62_V,
        seed_63_V_read => input_63_V,
        seed_64_V_read => input_64_V,
        seed_65_V_read => input_65_V,
        seed_66_V_read => input_66_V,
        seed_67_V_read => input_67_V,
        seed_68_V_read => input_68_V,
        seed_69_V_read => input_69_V,
        seed_70_V_read => input_70_V,
        seed_71_V_read => input_71_V,
        ap_return_0 => grp_buffer_input_fu_1250_ap_return_0,
        ap_return_1 => grp_buffer_input_fu_1250_ap_return_1,
        ap_return_2 => grp_buffer_input_fu_1250_ap_return_2,
        ap_return_3 => grp_buffer_input_fu_1250_ap_return_3,
        ap_return_4 => grp_buffer_input_fu_1250_ap_return_4,
        ap_return_5 => grp_buffer_input_fu_1250_ap_return_5,
        ap_return_6 => grp_buffer_input_fu_1250_ap_return_6,
        ap_return_7 => grp_buffer_input_fu_1250_ap_return_7,
        ap_return_8 => grp_buffer_input_fu_1250_ap_return_8,
        ap_return_9 => grp_buffer_input_fu_1250_ap_return_9,
        ap_return_10 => grp_buffer_input_fu_1250_ap_return_10,
        ap_return_11 => grp_buffer_input_fu_1250_ap_return_11,
        ap_return_12 => grp_buffer_input_fu_1250_ap_return_12,
        ap_return_13 => grp_buffer_input_fu_1250_ap_return_13,
        ap_return_14 => grp_buffer_input_fu_1250_ap_return_14,
        ap_return_15 => grp_buffer_input_fu_1250_ap_return_15,
        ap_return_16 => grp_buffer_input_fu_1250_ap_return_16,
        ap_return_17 => grp_buffer_input_fu_1250_ap_return_17,
        ap_return_18 => grp_buffer_input_fu_1250_ap_return_18,
        ap_return_19 => grp_buffer_input_fu_1250_ap_return_19,
        ap_return_20 => grp_buffer_input_fu_1250_ap_return_20,
        ap_return_21 => grp_buffer_input_fu_1250_ap_return_21,
        ap_return_22 => grp_buffer_input_fu_1250_ap_return_22,
        ap_return_23 => grp_buffer_input_fu_1250_ap_return_23,
        ap_return_24 => grp_buffer_input_fu_1250_ap_return_24,
        ap_return_25 => grp_buffer_input_fu_1250_ap_return_25,
        ap_return_26 => grp_buffer_input_fu_1250_ap_return_26,
        ap_return_27 => grp_buffer_input_fu_1250_ap_return_27,
        ap_return_28 => grp_buffer_input_fu_1250_ap_return_28,
        ap_return_29 => grp_buffer_input_fu_1250_ap_return_29,
        ap_return_30 => grp_buffer_input_fu_1250_ap_return_30,
        ap_return_31 => grp_buffer_input_fu_1250_ap_return_31,
        ap_return_32 => grp_buffer_input_fu_1250_ap_return_32,
        ap_return_33 => grp_buffer_input_fu_1250_ap_return_33,
        ap_return_34 => grp_buffer_input_fu_1250_ap_return_34,
        ap_return_35 => grp_buffer_input_fu_1250_ap_return_35,
        ap_return_36 => grp_buffer_input_fu_1250_ap_return_36,
        ap_return_37 => grp_buffer_input_fu_1250_ap_return_37,
        ap_return_38 => grp_buffer_input_fu_1250_ap_return_38,
        ap_return_39 => grp_buffer_input_fu_1250_ap_return_39,
        ap_return_40 => grp_buffer_input_fu_1250_ap_return_40,
        ap_return_41 => grp_buffer_input_fu_1250_ap_return_41,
        ap_return_42 => grp_buffer_input_fu_1250_ap_return_42,
        ap_return_43 => grp_buffer_input_fu_1250_ap_return_43,
        ap_return_44 => grp_buffer_input_fu_1250_ap_return_44,
        ap_return_45 => grp_buffer_input_fu_1250_ap_return_45,
        ap_return_46 => grp_buffer_input_fu_1250_ap_return_46,
        ap_return_47 => grp_buffer_input_fu_1250_ap_return_47,
        ap_return_48 => grp_buffer_input_fu_1250_ap_return_48,
        ap_return_49 => grp_buffer_input_fu_1250_ap_return_49,
        ap_return_50 => grp_buffer_input_fu_1250_ap_return_50,
        ap_return_51 => grp_buffer_input_fu_1250_ap_return_51,
        ap_return_52 => grp_buffer_input_fu_1250_ap_return_52,
        ap_return_53 => grp_buffer_input_fu_1250_ap_return_53,
        ap_return_54 => grp_buffer_input_fu_1250_ap_return_54,
        ap_return_55 => grp_buffer_input_fu_1250_ap_return_55,
        ap_return_56 => grp_buffer_input_fu_1250_ap_return_56,
        ap_return_57 => grp_buffer_input_fu_1250_ap_return_57,
        ap_return_58 => grp_buffer_input_fu_1250_ap_return_58,
        ap_return_59 => grp_buffer_input_fu_1250_ap_return_59,
        ap_return_60 => grp_buffer_input_fu_1250_ap_return_60,
        ap_return_61 => grp_buffer_input_fu_1250_ap_return_61,
        ap_return_62 => grp_buffer_input_fu_1250_ap_return_62,
        ap_return_63 => grp_buffer_input_fu_1250_ap_return_63,
        ap_return_64 => grp_buffer_input_fu_1250_ap_return_64,
        ap_return_65 => grp_buffer_input_fu_1250_ap_return_65,
        ap_return_66 => grp_buffer_input_fu_1250_ap_return_66,
        ap_return_67 => grp_buffer_input_fu_1250_ap_return_67,
        ap_return_68 => grp_buffer_input_fu_1250_ap_return_68,
        ap_return_69 => grp_buffer_input_fu_1250_ap_return_69,
        ap_return_70 => grp_buffer_input_fu_1250_ap_return_70,
        ap_return_71 => grp_buffer_input_fu_1250_ap_return_71);

    output_0_V <= grp_buffer_input_fu_1250_ap_return_0;
    output_10_V <= grp_buffer_input_fu_1250_ap_return_10;
    output_11_V <= grp_buffer_input_fu_1250_ap_return_11;
    output_12_V <= grp_buffer_input_fu_1250_ap_return_12;
    output_13_V <= grp_buffer_input_fu_1250_ap_return_13;
    output_14_V <= grp_buffer_input_fu_1250_ap_return_14;
    output_15_V <= grp_buffer_input_fu_1250_ap_return_15;
    output_16_V <= grp_buffer_input_fu_1250_ap_return_16;
    output_17_V <= grp_buffer_input_fu_1250_ap_return_17;
    output_18_V <= grp_buffer_input_fu_1250_ap_return_18;
    output_19_V <= grp_buffer_input_fu_1250_ap_return_19;
    output_1_V <= grp_buffer_input_fu_1250_ap_return_1;
    output_20_V <= grp_buffer_input_fu_1250_ap_return_20;
    output_21_V <= grp_buffer_input_fu_1250_ap_return_21;
    output_22_V <= grp_buffer_input_fu_1250_ap_return_22;
    output_23_V <= grp_buffer_input_fu_1250_ap_return_23;
    output_24_V <= grp_buffer_input_fu_1250_ap_return_24;
    output_25_V <= grp_buffer_input_fu_1250_ap_return_25;
    output_26_V <= grp_buffer_input_fu_1250_ap_return_26;
    output_27_V <= grp_buffer_input_fu_1250_ap_return_27;
    output_28_V <= grp_buffer_input_fu_1250_ap_return_28;
    output_29_V <= grp_buffer_input_fu_1250_ap_return_29;
    output_2_V <= grp_buffer_input_fu_1250_ap_return_2;
    output_30_V <= grp_buffer_input_fu_1250_ap_return_30;
    output_31_V <= grp_buffer_input_fu_1250_ap_return_31;
    output_32_V <= grp_buffer_input_fu_1250_ap_return_32;
    output_33_V <= grp_buffer_input_fu_1250_ap_return_33;
    output_34_V <= grp_buffer_input_fu_1250_ap_return_34;
    output_35_V <= grp_buffer_input_fu_1250_ap_return_35;
    output_36_V <= grp_buffer_input_fu_1250_ap_return_36;
    output_37_V <= grp_buffer_input_fu_1250_ap_return_37;
    output_38_V <= grp_buffer_input_fu_1250_ap_return_38;
    output_39_V <= grp_buffer_input_fu_1250_ap_return_39;
    output_3_V <= grp_buffer_input_fu_1250_ap_return_3;
    output_40_V <= grp_buffer_input_fu_1250_ap_return_40;
    output_41_V <= grp_buffer_input_fu_1250_ap_return_41;
    output_42_V <= grp_buffer_input_fu_1250_ap_return_42;
    output_43_V <= grp_buffer_input_fu_1250_ap_return_43;
    output_44_V <= grp_buffer_input_fu_1250_ap_return_44;
    output_45_V <= grp_buffer_input_fu_1250_ap_return_45;
    output_46_V <= grp_buffer_input_fu_1250_ap_return_46;
    output_47_V <= grp_buffer_input_fu_1250_ap_return_47;
    output_48_V <= grp_buffer_input_fu_1250_ap_return_48;
    output_49_V <= grp_buffer_input_fu_1250_ap_return_49;
    output_4_V <= grp_buffer_input_fu_1250_ap_return_4;
    output_50_V <= grp_buffer_input_fu_1250_ap_return_50;
    output_51_V <= grp_buffer_input_fu_1250_ap_return_51;
    output_52_V <= grp_buffer_input_fu_1250_ap_return_52;
    output_53_V <= grp_buffer_input_fu_1250_ap_return_53;
    output_54_V <= grp_buffer_input_fu_1250_ap_return_54;
    output_55_V <= grp_buffer_input_fu_1250_ap_return_55;
    output_56_V <= grp_buffer_input_fu_1250_ap_return_56;
    output_57_V <= grp_buffer_input_fu_1250_ap_return_57;
    output_58_V <= grp_buffer_input_fu_1250_ap_return_58;
    output_59_V <= grp_buffer_input_fu_1250_ap_return_59;
    output_5_V <= grp_buffer_input_fu_1250_ap_return_5;
    output_60_V <= grp_buffer_input_fu_1250_ap_return_60;
    output_61_V <= grp_buffer_input_fu_1250_ap_return_61;
    output_62_V <= grp_buffer_input_fu_1250_ap_return_62;
    output_63_V <= grp_buffer_input_fu_1250_ap_return_63;
    output_64_V <= grp_buffer_input_fu_1250_ap_return_64;
    output_65_V <= grp_buffer_input_fu_1250_ap_return_65;
    output_66_V <= grp_buffer_input_fu_1250_ap_return_66;
    output_67_V <= grp_buffer_input_fu_1250_ap_return_67;
    output_68_V <= grp_buffer_input_fu_1250_ap_return_68;
    output_69_V <= grp_buffer_input_fu_1250_ap_return_69;
    output_6_V <= grp_buffer_input_fu_1250_ap_return_6;
    output_70_V <= grp_buffer_input_fu_1250_ap_return_70;
    output_71_V <= grp_buffer_input_fu_1250_ap_return_71;
    output_7_V <= grp_buffer_input_fu_1250_ap_return_7;
    output_8_V <= grp_buffer_input_fu_1250_ap_return_8;
    output_9_V <= grp_buffer_input_fu_1250_ap_return_9;
end behav;
